# Generated by Django 4.2.4 on 2023-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/iamges/avatar.svg', null=True, upload_to=''),
        ),
    ]
